#use_frameworks!

platform :ios, '8.0'

target 'SGPay_Example' do
  pod 'SGPay', :path => '../'

  target 'SGPay_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
